"""Fixed telegram in user model

Revision ID: f1ac1a990a36
Revises: 92fb2687a964
Create Date: 2024-09-04 13:48:44.198406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ac1a990a36'
down_revision = '92fb2687a964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('telegram',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_index('ix_users_telegram')
        batch_op.create_index(batch_op.f('ix_users_telegram'), ['telegram'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram'))
        batch_op.create_index('ix_users_telegram', ['telegram'], unique=1)
        batch_op.alter_column('telegram',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
